version: 2
enable-beta-ecosystems: true # Julia ecosystem
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "github-actions"
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/test"
    schedule:
      interval: "daily"
    groups:
      all-julia-packages:
        patterns:
          - "*"
